ConcertBooking.UI/Models/ErrorViewModel.cs
namespace ConcertBooking.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConcertBooking.UI/ViewModels/ConvertViewModel/ConcertViewModel.cs
namespace ConcertBooking.UI.ViewModels.ConvertViewModel
{
    public class ConcertViewModel
    {
        public int ID { get; set; }
        public int VenueID { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public string VenueName { get; set; }
        public string VenueAddress { get; set; }
    }
}

ConcertBooking.UI/ViewModels/ConvertViewModel/CreateConcertViewModel.cs
using ConcertBooking.Entities;

namespace ConcertBooking.UI.ViewModels.ConvertViewModel
{
    public class CreateConcertViewModel
    {
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public int VenueID { get; set; }
    }
}

ConcertBooking.UI/ViewModels/VenueViewModel/CreateVenueViewModel.cs
namespace ConcertBooking.UI.ViewModels.VenueViewModel
{
    public class CreateVenueViewModel
    {    
        public string Name { get; set; }
        public string Address { get; set; }
    }
}

ConcertBooking.UI/ViewModels/VenueViewModel/VenueViewModel.cs
namespace ConcertBooking.UI.ViewModels.VenueViewModel
{
    public class VenueViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
}

ConcertBooking.UI/Controllers/ConcertController.cs
using AutoMapper;
using ConcertBooking.UI.ViewModels.ConvertViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ConcertBooking.Entities;
using ConcertBooking.Repositories.Interfaces;
using System;

namespace ConcertBooking.UI.Controllers
{
    public class ConcertController : Controller
    {
        private IConcertRepo _concertRepo;
        private IVenueRepo _venueRepo;
        private IMapper _mapper;
        public ConcertController(IConcertRepo concertRepo, IVenueRepo venueRepo,IMapper mapper)
        {
            _concertRepo = concertRepo;
            _venueRepo = venueRepo;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {            
            var concerts = await _concertRepo.GetAll();
            var model = _mapper.Map<List<ConcertViewModel>>(concerts);           
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var venue = await _venueRepo.GetAll();
            ViewBag.venueList = new SelectList(venue, "ID", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateConcertViewModel vm)
        {
            var model = _mapper.Map<Concert>(vm);            
            await _concertRepo.SaveEntity(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var concert = await _concertRepo.GetById(id);
            var model = _mapper.Map<ConcertViewModel>(concert);            
            var venue = await _venueRepo.GetAll();
            ViewBag.venueList = new SelectList(venue, "ID", "Name");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ConcertViewModel vm)
        {
            var model = _mapper.Map<Concert>(vm);
            await _concertRepo.UpdateEntity(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var venue = await _concertRepo.GetById(id);
            await _concertRepo.DeleteEntity(venue);
            return RedirectToAction("Index");
        }
    }
}

ConcertBooking.UI/Controllers/HomeController.cs
using ConcertBooking.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConcertBooking.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConcertBooking.UI/Controllers/VenueController.cs
using AutoMapper;
using ConcertBooking.UI.ViewModels.VenueViewModel;
using Microsoft.AspNetCore.Mvc;
using ConcertBooking.Entities;
using ConcertBooking.Repositories.Interfaces;

namespace ConcertBooking.UI.Controllers
{
    public class VenueController : Controller
    {
        private IVenueRepo _venueRepo;
        private IMapper _mapper;

        public VenueController(IVenueRepo venueRepo, IMapper mapper)
        {
            _venueRepo = venueRepo;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var venues = await _venueRepo.GetAll();
            var vm = _mapper.Map<List<VenueViewModel>>(venues);
            return View(vm);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateVenueViewModel vm)
        {
            var model = _mapper.Map<Venue>(vm);
            await _venueRepo.SaveEntity(model);  // Task.CompletedTask
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var venue = await _venueRepo.GetById(id);
            var vm = _mapper.Map<VenueViewModel>(venue);
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VenueViewModel vm)
        {
            var model = _mapper.Map<Venue>(vm);
            await _venueRepo.UpdateEntity(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var venue = await _venueRepo.GetById(id);
            await _venueRepo.DeleteEntity(venue);
            return RedirectToAction("Index");
        }
    }
}

ConcertBooking.UI/Views/Concert/Create.cshtml
@model CreateConcertViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Create Concert</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VenueID" class="control-label"></label>
                <select asp-for="VenueID" asp-items="@ViewBag.venueList" class="form-control">
                    <option value="-1">Select Venue</option>
                </select>
                <span asp-validation-for="VenueID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConcertBooking.UI/Views/Concert/Edit.cshtml
@model ConcertViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ConcertViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VenueID" class="control-label"></label>
                <select asp-for="VenueID" asp-items="@ViewBag.venueList" class="form-control">
                    <option value="-1">Select Venue</option>
                </select>
                <span asp-validation-for="VenueID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConcertBooking.UI/Views/Concert/Index.cshtml
@model IEnumerable<ConcertBooking.UI.ViewModels.ConvertViewModel.ConcertViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Concert List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.VenueID)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VenueName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VenueAddress)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
           @*  <td>
                @Html.DisplayFor(modelItem => item.VenueID)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VenueName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VenueAddress)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |                
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

ConcertBooking.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ConcertBooking.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConcertBooking.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConcertBooking.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConcertBooking.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Concert" asp-action="Index">Concert</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venue" asp-action="Index">Venue</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ConcertBooking.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ConcertBooking.UI/Views/Venue/Create.cshtml
@model CreateVenueViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Venue</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConcertBooking.UI/Views/Venue/Edit.cshtml
@model ConcertBooking.UI.ViewModels.VenueViewModel.VenueViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Venue</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input  type="hidden" id="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConcertBooking.UI/Views/Venue/Index.cshtml
@model IEnumerable<VenueViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Venue List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>